### ISSUE TITLE
个人问题

### ISSUE THREAD

**Issue by jdljdljdl** [khinggan/turtlebot3_formation#2]
博主您好，我想问一下，您这个项目中的leader_follow.launch是否借鉴过turtlebot3_follower.launch，关于这个文件，我在官网寻找不到，但是却在别人的文档里面见到了需要启动这个launch，我不知道您的这个launch适配度高不高

**Comment by khinggan** [comment]
你好，我参考的是[abcswarm leader follower](https://github.com/tianbot/abc_swarm/blob/main/launch/demo/demo_sim_leader_follower.launch)。

**Comment by khinggan** [comment]
> 您这个项目中的leader_follow.launch是否借鉴过turtlebot3_follower.launch

你值得`turtlebot3_follower.launch`是[turtlebot3官网turtlebot3_follower.launch](https://github.com/ROBOTIS-GIT/turtlebot3_applications/blob/master/turtlebot3_follower/launch/turtlebot3_follower.launch)吗？

**Comment by jdljdljdl** [comment]
> > 您这个项目中的leader_follow.launch是否借鉴过turtlebot3_follower.launch
> 
> 你值得`turtlebot3_follower.launch`是[turtlebot3官网turtlebot3_follower.launch](https://github.com/ROBOTIS-GIT/turtlebot3_applications/blob/master/turtlebot3_follower/launch/turtlebot3_follower.launch)吗？

是的，但是我在官网没有找到啊┭┮﹏┭┮
